In [1]:
import pandas as pd

In [2]:
name = "zybook_05_28"

In [3]:
def run_code(name):
    zybook = pd.read_csv(name+'.csv')
    zybook_col = [i for i in zybook.columns if ('Participation' in i or 'Challenge' in i) and ('total' not in i)]
    print(zybook_col)
    zybook[name] = zybook[zybook_col].mean(axis=1)
    columns = [i for i in zybook.columns if 'zybook' in i]
    zybook = zybook[['Last name','First name','Primary email',name]]
    for column in columns:
        zybook[column] = zybook[column].apply(lambda x: 5 if x>80 else (3 if x>60 else (1 if x>40 else 0)))
    tritoned = pd.read_csv('canvas.csv')[['SIS Login ID','Student','SIS User ID']]
    zybook['id'] = zybook['Primary email'].apply(lambda x: x.split('@')[0])
    output = tritoned.merge(zybook,left_on='SIS Login ID', right_on = 'id',how='left')
    output[name] = output[name].fillna(0)
    output.to_csv('output.csv')
    output = tritoned.merge(zybook,left_on='SIS Login ID', right_on = 'id',how='outer')
    return output

In [4]:
output = run_code(name)

['10.7 - Participation (19)', '10.8 - Participation (17)']

In [5]:
output[output['Student'].isna()]

,SIS Login ID,Student,SIS User ID,Last name,First name,Primary email,zybook_05_28,id
151,NaN,NaN,NaN,Almusallam,Mishari,malmusal@ucsd.edu,0.0,malmusal
152,NaN,NaN,NaN,Bethamcharla,Lakshmikethan,lbethamcharla@ucsd.edu,0.0,lbethamcharla
153,NaN,NaN,NaN,Carbajal,Cristian,c3carbaj@ucsd.edu,0.0,c3carbaj
154,NaN,NaN,NaN,Carrion,Dean,dcarrion@ucsd.edu,0.0,dcarrion
155,NaN,NaN,NaN,Choi,Seung,swc001@ucsd.edu,0.0,swc001
156,NaN,NaN,NaN,Garcia-Perez,Michael,mig009@ucsd.edu,0.0,mig009
157,NaN,NaN,NaN,Hamideh,Mohammed,mhamideh@ucsd.edu,0.0,mhamideh
158,NaN,NaN,NaN,Kurpanek,Tyler,tkurpane@ucsd.edu,0.0,tkurpane
159,NaN,NaN,NaN,Long,Yunfan,yulong@ucsd.edu,0.0,yulong
160,NaN,NaN,NaN,Malhotra,Niharika,n1malhot@ucsd.edu,0.0,n1malhot
161,NaN,NaN,NaN,Muir,Akshat,akmuir@ucsd.edu,0.0,akmuir
162,NaN,NaN,NaN,Padayao,Alex,adpadaya@ucsd.edu,0.0,adpadaya
163,NaN,NaN,NaN,Pant,Raghav,raghav0206@hotmail.com,0.0,raghav0206
164,NaN,NaN,NaN,Quan,Yulong,y6quan@ucsd.edu,0.0,y6quan
165,NaN,NaN,NaN,Serrano,Sinjin,smserrano@ucsd.edu,0.0,smserrano
166,NaN,NaN,NaN,Soohoo,Austin,asoohoo@ucsd.edu,0.0,asoohoo
167,NaN,NaN,NaN,Thai,Martin,mtthai@ucsd.edu,0.0,mtthai
168,NaN,NaN,NaN,xiao,jinxin,j5xiao@ucsd.edu,0.0,j5xiao
169,NaN,NaN,NaN,Zhang,Zhuji,zhz044@ucsd.edu,0.0,zhz044